export { A_Match } from './Match/A_Match';
export { A_MatchPlay } from './Match/A_MatchPlay';
export { A_Result } from './Match/A_Result';
export { A_ResultSerie } from './Match/A_ResultSerie';
export { A_Serie } from './Match/A_Serie';
export { Person } from './Person';
export type { IPersonData } from './Person';
export { Team, TeamMatch } from './Team';
export type { ITeamCreator, ITeamOwner } from './Team';
export { CATEGORIES, getCategoryList } from './types';
export type { TypeMatchState } from './Match/A_Match';
export type { IA_ResultInfo, TypeTotalScore } from './Match/A_Result';
export type { IA_ResultSerieInfo } from './Match/A_ResultSerie';
export type { TMatchScore, TSerieScore } from './Match/scores';
export type { ISportProfile, AnySportProfile, IMatchCreationInfo, ISerieCreationInfo } from './profiles/ISportProfile';
export { A_TeamTableItem, AnyTeamTableItem } from './profiles/A_TeamTableItem';
export type { arr2, TypeBaseStageOption, TypeCategory, TypeCategoryList } from './types';
